---
version: "3.2"

services:
  tinylist:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROD: 'true'
        DB_URL: http://192.168.1.5
        DB_PORT: 5984
        DB_USER: tinylist
        DB_PASS: tinylist
        CREATE_DB_URL: 'http://192.168.1.5:5984'
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: couchdb
    environment:
      COUCHDB_USER: tinylist
      COUCHDB_PASSWORD: tinylist
    volumes:
      - /mnt/data/couchdb:/opt/couchdb/data
    ports:
      - "5984:5984"


